apiVersion: v1
kind: Pod
metadata:
  name: express-test
  namespace: express-nodejs
  labels:
    app: express-test
spec:
  containers:
  - name: express-test
    image: lukondefmwila/express-test:1.0.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
