apiVersion: v1
kind: Service
metadata:
  name: express-test-svc
  namespace: express-nodejs
spec:
  selector:
    app: express-test
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
